version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=boilerplate_db
      - DB_USER=pguser
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=boilerplate_db
    volumes:
      - boilerplate_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  boilerplate_data:
    name: boilerplate_data
